const stateStyles = {
  Pending: 'bg-slate-700 text-slate-200', Open: 'bg-cyan-500/15 text-cyan-200', 'In Progress': 'bg-cyan-500/15 text-cyan-200', 'Work in Progress': 'bg-cyan-500/15 text-cyan-200', New: 'bg-slate-700 text-slate-200', Assess: 'bg-indigo-500/15 text-indigo-200', Closed: 'bg-emerald-500/15 text-emerald-200', 'Closed Complete': 'bg-emerald-500/15 text-emerald-200', 'Closed Incomplete': 'bg-slate-700 text-slate-300', 'Closed Skipped': 'bg-slate-700 text-slate-300', Canceled: 'bg-slate-700 text-slate-300',
}

function journalValue(entry) { return typeof entry === 'string' ? entry : entry.value || entry.text }
function journalTime(entry) { return typeof entry === 'string' ? '' : entry.sys_created_on || entry.timestamp }
function newestFirst(entries) { return [...entries].sort((left, right) => journalTime(right).localeCompare(journalTime(left))) }
function isHumanJournalEntry(entry) { if (typeof entry === 'string') return true; const role = entry.role || ''; const author = entry.author || entry.sys_created_by || ''; return role !== 'System' && !author.toLowerCase().includes('system') && !author.toLowerCase().includes('atlas monitoring') }

export function PinnedAttachments({ attachments = [] }) {
  if (!attachments.length) return null
  return <div className="mb-4 rounded-lg border border-cyan-500/30 bg-cyan-950/20 p-3"><p className="text-xs font-bold uppercase tracking-wider text-cyan-100">📎 Pinned Evidence &amp; Attachments</p><div className="mt-3 flex flex-wrap gap-2">{attachments.map((attachment) => { const isPdf = attachment.content_type === 'application/pdf' || attachment.filename?.toLowerCase().endsWith('.pdf'); return <a key={`${attachment.filename}-${attachment.url}`} href={attachment.url} target="_blank" rel="noreferrer" className={`inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-semibold transition hover:bg-slate-800 ${isPdf ? 'border-rose-500/40 bg-rose-950/30 text-rose-100' : 'border-sky-500/40 bg-sky-950/30 text-sky-100'}`}><span aria-hidden="true">{isPdf ? '📄' : '🖼️'}</span><span>{attachment.filename}</span><span className="text-slate-400">{attachment.size}</span><span>{isPdf ? '📄 View PDF ↗' : '🖼️ View Image ↗'}</span></a> })}</div></div>
}

export function Journal({ comments = [] }) {
  const stream = newestFirst(comments.filter(isHumanJournalEntry))
  return <section className="rounded-xl border border-indigo-400/40 bg-slate-950/50 p-4"><h3 className="text-sm font-bold text-indigo-100">💬 Customer &amp; Support Journal ({stream.length})</h3><div className="max-h-64 overflow-y-auto pr-2 space-y-3 custom-scrollbar scrollbar-thin scrollbar-thumb-slate-700 scrollbar-track-transparent border border-slate-800/80 rounded-lg p-3 bg-slate-900/40 mt-4">{stream.length ? stream.map((comment, index) => { const customer = typeof comment !== 'string' && (comment.is_customer || comment.role === 'Requester'); const author = typeof comment === 'string' ? 'ServiceNow journal' : comment.author || comment.sys_created_by; return <article key={comment.id || comment.sys_id || `${journalValue(comment)}-${index}`} className="rounded-lg border border-slate-700 bg-slate-900/60 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><span className={`rounded-full border px-2 py-1 text-xs font-semibold ${customer ? 'border-cyan-400/40 bg-cyan-500/10 text-cyan-100' : 'border-indigo-400/40 bg-indigo-500/10 text-indigo-100'}`}>{customer ? '👤 Requester' : '🎧 L2 Support'} · {author}</span><span className="text-xs text-slate-500">{journalTime(comment)}</span></div><p className="mt-3 text-sm leading-6 text-slate-300">{journalValue(comment)}</p></article> }) : <p className="text-sm text-slate-500">No human journal updates recorded.</p>}</div></section>
}

function ChildTicket({ incident }) {
  const comments = newestFirst((incident.comments || []).filter(isHumanJournalEntry))
  return <li className="rounded-lg bg-slate-950/60 p-3"><div className="flex items-center justify-between gap-3"><div><p className="font-mono text-xs text-cyan-300">{incident.number}</p><p className="mt-1 text-sm text-slate-300">{incident.short_description}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-xs font-semibold ${stateStyles[incident.state] || stateStyles.Pending}`}>{incident.state}</span></div>{comments.length ? <div className="mt-3 space-y-2 border-t border-slate-800 pt-3">{comments.map((comment, index) => { const role = comment.role || (comment.is_customer ? 'Requester' : 'L2 Support'); const author = comment.author || comment.sys_created_by || 'ServiceNow journal'; return <article key={comment.id || comment.sys_id || `${journalValue(comment)}-${index}`} className="rounded-md border border-slate-700 bg-slate-900/70 p-2.5"><div className="flex flex-wrap items-center justify-between gap-2"><span className="rounded-full border border-indigo-400/40 bg-indigo-500/10 px-2 py-1 text-xs font-semibold text-indigo-100">Child Update · {incident.number}</span><span className="text-[11px] text-slate-500">{journalTime(comment)}</span></div><p className="mt-2 text-xs font-semibold text-cyan-100">{role === 'Requester' ? '👤' : '🎧'} {role} · {author}</p><p className="mt-1 text-xs leading-5 text-slate-300">{journalValue(comment)}</p></article> })}</div> : null}{incident.close_notes && <p className="mt-2 border-t border-slate-800 pt-2 text-xs leading-5 text-slate-400"><span className="font-semibold text-slate-300">Closure Notes:</span> {incident.close_notes}</p>}</li>
}

export function ChildIncidents({ incidents = [] }) {
  return <section className="rounded-xl border border-slate-700 bg-slate-950/40 p-4"><h3 className="text-sm font-semibold">Child Tickets ({incidents.length})</h3>{incidents.length ? <ul className="mt-3 space-y-3">{incidents.map((incident) => <ChildTicket key={incident.sys_id || incident.number} incident={incident} />)}</ul> : <p className="mt-3 text-sm text-slate-500">No child incidents linked to this record.</p>}</section>
}

export default function WorkItemActivities({ ticket }) {
  return <><ChildIncidents incidents={ticket.type === 'INC' ? ticket.child_incidents : []} /><PinnedAttachments attachments={ticket.attachments} /><Journal comments={ticket.comments} /></>
}
